FROM python:3.12-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy spider code
COPY spider /app/spider

# Create sessions directory
RUN mkdir -p /app/sessions

# Run spider
CMD ["python", "-m", "spider.main"]
